// 三年级下册全册完整字词句大词库 - 26春生字词句专项版
const wordLib = [
  // ================= 第一单元 =================
  // 第1课《古诗三首》
  { unit: "1", lessonId: "1", word: "融化", pinyin: "róng huà", sentence: "春天来了，河里的冰雪慢慢[融化]了。", target: "融化", targetPinyin: "róng huà" },
  { unit: "1", lessonId: "1", word: "燕子", pinyin: "yàn zi", sentence: "小[燕子]穿着黑衣裳，在屋檐下筑巢呢。", target: "燕子", targetPinyin: "yàn zi" },
  { unit: "1", lessonId: "1", word: "鸳鸯", pinyin: "yuān yāng", sentence: "[鸳鸯]总是成对地在湖面上游来游去。", target: "鸳鸯", targetPinyin: "yuān yāng" },
  { unit: "1", lessonId: "1", word: "嫩芽", pinyin: "nèn yá", sentence: "泥土里的种子冒出了[嫩芽]。", target: "嫩芽", targetPinyin: "nèn yá" },
  { unit: "1", lessonId: "1", word: "梅花", pinyin: "méi huā", sentence: "寒冬里，[梅花]迎着风雪开放了。", target: "梅花", targetPinyin: "méi huā" },
  { unit: "1", lessonId: "1", word: "泛舟", pinyin: "fàn zhōu", sentence: "小船在湖面上[泛]着，慢慢向前漂。", target: "泛", targetPinyin: "fàn" },
  { unit: "1", lessonId: "1", word: "减少", pinyin: "jiǎn shǎo", sentence: "做数学题时，别忘记用减法计算以[减少]错误。", target: "减少", targetPinyin: "jiǎn shǎo" },
  { unit: "1", lessonId: "1", word: "河豚", pinyin: "hé tún", sentence: "河[豚]欢快地游着，吐出一串串泡泡。", target: "豚", targetPinyin: "tún" },
  { unit: "1", lessonId: "1", word: "曾经", pinyin: "céng jīng", sentence: "我[曾经]去过那个城市，也听说了一些故事。", target: "曾经", targetPinyin: "céng jīng" },

  // 第2课《燕子》
  { unit: "1", lessonId: "2", word: "凑近", pinyin: "còu jìn", sentence: "小朋友们[凑]到一起，开心地玩起了游戏。", target: "凑", targetPinyin: "còu" },
  { unit: "1", lessonId: "2", word: "活泼", pinyin: "huó pō", sentence: "弟弟拿起水杯，不小心把水[泼]到了地上。", target: "泼", targetPinyin: "pō" },
  { unit: "1", lessonId: "2", word: "集合", pinyin: "jí hé", sentence: "早上的[集]市真热闹，有卖菜的也有卖水果的。", target: "集", targetPinyin: "jí" },
  { unit: "1", lessonId: "2", word: "偶尔", pinyin: "ǒu ěr", sentence: "我[偶尔]会和妈妈一起去公园散步。", target: "偶尔", targetPinyin: "ǒu ěr" },
  { unit: "1", lessonId: "2", word: "沾水", pinyin: "zhān shuǐ", sentence: "小猫的爪子[沾]到了墨水，在纸上印出了小梅花。", target: "沾", targetPinyin: "zhān" },
  { unit: "1", lessonId: "2", word: "空闲", pinyin: "kòng xián", sentence: "爷爷[空闲]的时候，喜欢坐在院子里喝茶。", target: "空闲", targetPinyin: "kòng xián" },
  { unit: "1", lessonId: "2", word: "纤细", pinyin: "xiān xì", sentence: "柳树的枝条[纤]长柔软，在风中轻轻摆动。", target: "纤", targetPinyin: "xiān" },
  { unit: "1", lessonId: "2", word: "旗杆", pinyin: "qí gān", sentence: "国旗在飘扬的旗[杆]下记录老师讲话。", target: "杆", targetPinyin: "gān" },
  { unit: "1", lessonId: "2", word: "伶俐", pinyin: "líng lì", sentence: "小红是个伶牙[俐]齿的小姑娘，特别会说话。", target: "俐", targetPinyin: "lì" },
  { unit: "1", lessonId: "2", word: "空旷", pinyin: "kōng kuàng", sentence: "郊外的田野十分[空旷]，能看到很远的地方。", target: "空旷", targetPinyin: "kōng kuàng" },
  { unit: "1", lessonId: "2", word: "横着", pinyin: "héng zhe", sentence: "马路边[横]着一根木头，大家走路要小心。", target: "横", targetPinyin: "héng" },
  { unit: "1", lessonId: "2", word: "翅膀", pinyin: "chì bǎng", sentence: "小鸟展开[翅膀]，扇动着羽翼飞向了蓝天。", target: "翅膀", targetPinyin: "chì bǎng" },
  { unit: "1", lessonId: "2", word: "荡漾", pinyin: "dàng yàng", sentence: "湖里扔一颗石子，水面上[荡漾]起一圈圈波纹。", target: "荡漾", targetPinyin: "dàng yàng" },
  { unit: "1", lessonId: "2", word: "疲倦", pinyin: "pí juàn", sentence: "放学回家后，我有点[疲倦]，只想坐在沙发上休息。", target: "疲倦", targetPinyin: "pí juàn" },
  { unit: "1", lessonId: "2", word: "散步", "pinyin": "sàn bù", sentence: "晚饭后，我和妈妈一起去公园[散]步。", target: "散", targetPinyin: "sàn" },
  { unit: "1", lessonId: "2", word: "痕迹", pinyin: "hén jì", sentence: "雨后的泥地上，留下了小狗的爪[痕]。", target: "痕", targetPinyin: "hén" },

  // 第3课《荷花》
  { unit: "1", lessonId: "3", word: "荷花", pinyin: "hé huā", sentence: "池塘里的[荷花]粉粉的，特别好看。", target: "荷花", targetPinyin: "hé huā" },
  { unit: "1", lessonId: "3", word: "挨着", pinyin: "āi zhe", sentence: "小明[挨]着墙站着，看着碎落一地的花瓶。", target: "挨", targetPinyin: "āi" },
  { unit: "1", lessonId: "3", word: "蓬松", pinyin: "péng sōng", sentence: "蒲公英的[蓬]球被风吹得飘走了。", target: "蓬", targetPinyin: "péng" },
  { unit: "1", lessonId: "3", word: "饱胀", pinyin: "bǎo zhàng", sentence: "小明吃得太饱，肚子都[胀]起来了。", target: "胀", targetPinyin: "zhàng" },
  { unit: "1", lessonId: "3", word: "分裂", pinyin: "fēn liè", sentence: "冬天太冷，水管冻[裂]了一条缝。", target: "裂", targetPinyin: "liè" },
  { unit: "1", lessonId: "3", word: "姿势", pinyin: "zī shì", sentence: "雄鹰展开翅膀，有一股飞翔的气[势]。", target: "势", targetPinyin: "shì" },
  { unit: "1", lessonId: "3", word: "微笑", pinyin: "wēi xiào", sentence: "妈妈的脸上露出了[微]笑。", target: "微", targetPinyin: "wēi" },
  { unit: "1", lessonId: "3", word: "笔记本", pinyin: "bǐ jì běn", sentence: "我把老师的话[记]在了笔记本上。", target: "记", targetPinyin: "jì" },
  { unit: "1", lessonId: "3", word: "衣裳", pinyin: "yī shang", sentence: "妹妹穿着漂亮的花[衣裳]在院子里跑。", target: "衣裳", targetPinyin: "yī shang" },
  { unit: "1", lessonId: "3", word: "翩翩", pinyin: "piān piān", sentence: "蝴蝶在花丛中[翩翩]飞舞。", target: "翩翩", targetPinyin: "piān piān" },
  { unit: "1", lessonId: "3", word: "蜻蜓", pinyin: "qīng tíng", sentence: "[蜻蜓]停在刚冒尖的荷叶上。", target: "蜻蜓", targetPinyin: "qīng tíng" },

  // 第4课《昆虫备忘录》
  { unit: "1", lessonId: "4", word: "记录", pinyin: "jì lù", sentence: "我用录音笔[录]下了老师讲的故事。", target: "录", targetPinyin: "lù" },
  { unit: "1", lessonId: "4", word: "琢磨", pinyin: "zuó mo", sentence: "工匠在仔细地雕[琢]一块玉石。", target: "琢", targetPinyin: "zuó" },
  { unit: "1", lessonId: "4", word: "灵敏", pinyin: "líng mǐn", sentence: "小猫的耳朵很[灵敏]，一点声音都能听到。", target: "灵敏", targetPinyin: "líng mǐn" },
  { unit: "1", lessonId: "4", word: "款式", pinyin: "kuǎn shì", sentence: "妈妈给我买了一[款]新的文具盒。", target: "款", targetPinyin: "kuǎn" },
  { unit: "1", lessonId: "4", word: "薄膜", pinyin: "bó mó", sentence: "葡萄外面有一层薄薄的保护[膜]。", target: "膜", targetPinyin: "mó" },
  { unit: "1", lessonId: "4", word: "变瞎", pinyin: "biàn xiā", sentence: "不要用手揉眼睛，不然容易变[瞎]。", target: "瞎", targetPinyin: "xiā" },
  { unit: "1", lessonId: "4", word: "有益", pinyin: "yǒu yì", sentence: "多吃蔬菜对身体有[益]处。", target: "益", targetPinyin: "yì" },
  { unit: "1", lessonId: "4", word: "一辆", pinyin: "yī liàng", sentence: "马路上开过一[辆]红色的小汽车。", target: "辆", targetPinyin: "liàng" },
  { unit: "1", lessonId: "4", word: "蚂蚁", pinyin: "mǎ yǐ", sentence: "草丛里有很多昆虫，有蚂蚱、[蚂]蚁、数也数不清。", target: "蚂", targetPinyin: "mǎ" },
  { unit: "1", lessonId: "4", word: "斑点", pinyin: "bān diǎn", sentence: "小豹子的身上有漂亮的[斑]点。", target: "斑", targetPinyin: "bān" },
  { unit: "1", lessonId: "4", word: "褐色", pinyin: "hè sè", sentence: "松鼠有一身[褐]色的皮毛。", target: "褐", targetPinyin: "hè" },

  // 语文园地一
  { unit: "1", lessonId: "29", word: "匕首", pinyin: "bǐ shǒu", sentence: "她用[匕]首小心翼翼的拆开了信封。", target: "匕", targetPinyin: "bǐ" },
  { unit: "1", lessonId: "29", word: "回忆", pinyin: "huí yì", sentence: "我常常回[忆]起和小伙伴在乡下玩耍的时光。", target: "忆", targetPinyin: "yì" },
  { unit: "1", lessonId: "29", word: "手艺", pinyin: "shǒu yì", sentence: "妹妹的绘画技[艺]越来越高了。", target: "艺", targetPinyin: "yì" },
  { unit: "1", lessonId: "29", word: "冗杂", pinyin: "rǒng zá", sentence: "写作文要简洁，不要有[冗]杂的语句。", target: "冗", targetPinyin: "rǒng" },
  { unit: "1", lessonId: "29", word: "黄犬", pinyin: "huáng quǎn", sentence: "邻居家的大黄[犬]很温顺，从不乱叫。", target: "犬", targetPinyin: "quǎn" },
  { unit: "1", lessonId: "29", word: "税款", pinyin: "shuì kuǎn", sentence: "爸爸妈妈工作后，都会依法缴纳[税]款。", target: "税", targetPinyin: "shuì" },
  { unit: "1", lessonId: "29", word: "兑换", pinyin: "duì huàn", sentence: "我用积分在商场[兑]换了一个可爱的笔记本。", target: "兑", targetPinyin: "duì" },
  { unit: "1", lessonId: "29", word: "执着", pinyin: "zhí zhuó", sentence: "哥哥对自己的梦想很[执]着，一直努力追求。", target: "执", targetPinyin: "zhí" },

  // ================= 第二单元 =================
  // 第5课《守株待兔》
  { unit: "2", lessonId: "5", word: "守护", pinyin: "shǒu hù", sentence: "小明每天都会[守]在窗边等妈妈下班。", target: "守", targetPinyin: "shǒu" },
  { unit: "2", lessonId: "5", word: "植株", pinyin: "zhí zhū", sentence: "农夫在田里发现了一[株]特别高的稻穗。", target: "株", targetPinyin: "zhū" },
  { unit: "2", lessonId: "5", word: "等待", pinyin: "děng dài", sentence: "我们要耐心等[待]公交车的到来。", target: "待", targetPinyin: "dài" },
  { unit: "2", lessonId: "5", word: "宋代", pinyin: "sòng dài", sentence: "[宋]代有很多著名的诗人和词人。", target: "宋", targetPinyin: "sòng" },
  { unit: "2", lessonId: "5", word: "耕种", pinyin: "gēng zhòng", sentence: "农民伯伯在春天里忙着[耕]田播种。", target: "耕", targetPinyin: "gēng" },
  { unit: "2", lessonId: "5", word: "折断", pinyin: "zhé duàn", sentence: "妹妹不小心[折]断了刚做好的纸飞机。", target: "折", targetPinyin: "zhé" },
  { unit: "2", lessonId: "5", word: "颈部", pinyin: "jǐng bù", sentence: "长[颈]鹿的长脖子能让它吃到高处的树叶。", target: "颈", targetPinyin: "jǐng" },
  { unit: "2", lessonId: "5", word: "解释", pinyin: "jiě shì", sentence: "老师耐心地为我们解[释]这道题的解法。", target: "释", targetPinyin: "shì" },
  { unit: "2", lessonId: "5", word: "其中", pinyin: "qí zhōng", sentence: "这本书的封面很精美，[其]内容也十分有趣。", target: "其", targetPinyin: "qi" },
  { unit: "2", lessonId: "5", word: "复习", pinyin: "fù xí", sentence: "学完课文后，我们当天要[复]习加深记忆。", target: "复", targetPinyin: "fù" },
  { unit: "2", lessonId: "5", word: "希冀", "pinyin": "xī jì", sentence: "我们[冀]望这次运动会能取得好成绩。", target: "冀", targetPinyin: "jì" },

  // 第6课《会摇尾巴的狼》
  { unit: "2", lessonId: "6", word: "装扮", pinyin: "zhuāng bàn", sentence: "妹妹喜欢把洋娃娃[装]进行李箱。", target: "装", targetPinyin: "zhuāng" },
  { unit: "2", lessonId: "6", word: "驯服", pinyin: "xùn fú", sentence: "叔叔能[驯]服山里的小野马。", target: "驯", targetPinyin: "xùn" },
  { unit: "2", lessonId: "6", word: "良好", pinyin: "liáng hǎo", sentence: "小狗是人类的[良]伴。", target: "良", targetPinyin: "liáng" },
  { unit: "2", lessonId: "6", word: "善良", pinyin: "shàn liáng", sentence: "奶奶总是[善]待身边的小动物。", target: "善", targetPinyin: "shàn" },
  { unit: "2", lessonId: "6", word: "伸展", pinyin: "shēn zhǎn", sentence: "我[伸]了个懒腰，准备开始写作业。", target: "伸", targetPinyin: "shēn" },
  { unit: "2", lessonId: "6", word: "谢谢", pinyin: "xiè xie", sentence: "得到帮助后，要主动说[谢]谢。", target: "谢", targetPinyin: "xiè" },
  { unit: "2", lessonId: "6", word: "灰尘", pinyin: "huī chén", sentence: "窗户上积了一层薄薄的灰[尘]。", target: "尘", targetPinyin: "chén" },
  { unit: "2", lessonId: "6", word: "凶狠", pinyin: "xiōng hěn", sentence: "他看起来[凶]，其实内心很温柔。", target: "凶", targetPinyin: "xiōng" },
  { unit: "2", lessonId: "6", word: "恶劣", pinyin: "è liè", sentence: "我们不能做[恶]意欺负同学的事。", target: "恶", targetPinyin: "è" },
  { unit: "2", lessonId: "6", word: "狠心", pinyin: "hěn xīn", sentence: "弟弟[狠]下心，把坏掉的玩具扔掉了。", target: "狠", targetPinyin: "hěn" },
  { unit: "2", lessonId: "6", word: "猎人", pinyin: "liè rén", sentence: "[猎]人在森林里寻找猎物。", target: "猎", targetPinyin: "liè" },
  { unit: "2", lessonId: "6", word: "收拾", pinyin: "shōu shi", sentence: "我弯腰[拾]起地上的铅笔。", target: "拾", targetPinyin: "shí" },
  { unit: "2", lessonId: "6", word: "模样", pinyin: "mú yàng", sentence: "他根据[模]样制作了一个模型。", target: "模", targetPinyin: "mú" },
  { unit: "2", lessonId: "6", word: "丝毫", pinyin: "sī háo", sentence: "今天数学课堂上我们学了关于[毫]米的知识。", target: "毫", targetPinyin: "háo" },
  { unit: "2", lessonId: "6", word: "犹如", pinyin: "yóu rú", sentence: "平静的湖面[犹如]一面硕大的平镜。", target: "犹如", targetPinyin: "yóu rú" },
  { unit: "2", lessonId: "6", word: "犹豫", pinyin: "yóu yù", sentence: "面对选择，他有些[犹豫]不定。", target: "犹豫", targetPinyin: "yóu yù" },
  { unit: "2", lessonId: "6", word: "狡猾", pinyin: "jiǎo huá", sentence: "狐狸是一种很[狡]猾的动物。", target: "狡", targetPinyin: "jiáo" },
  { unit: "2", lessonId: "6", word: "猾头", pinyin: "huá tóu", sentence: "狡猾的老鼠总能躲开猫的追[捕]。", target: "捕", targetPinyin: "bǔ" },
  { unit: "2", lessonId: "6", word: "互相", pinyin: "hù xiāng", sentence: "真相终于水落石出，我[相]信你，一定可以。", target: "相", targetPinyin: "xiāng" },

  // 第7课《鹿角和鹿腿》
  { unit: "2", lessonId: "7", word: "口渴", pinyin: "kǒu kě", sentence: "跑完步后，我感到非常口[渴]。", target: "渴", targetPinyin: "kě" },
  { unit: "2", lessonId: "7", word: "喝水", pinyin: "hē shuǐ", sentence: "妈妈让我[喝]一杯温牛奶再睡觉。", target: "喝", targetPinyin: "hē" },
  { unit: "2", lessonId: "7", word: "均匀", pinyin: "jūn yún", sentence: "我把蛋糕切成[匀]称的小块分给大家。", target: "匀", targetPinyin: "yún" },
  { unit: "2", lessonId: "7", word: "匀称", pinyin: "yún chèn", sentence: "你看这只狮子的身段多么[匀称]，强壮有力。", target: "匀称", targetPinyin: "yún chèn" },
  { unit: "2", lessonId: "7", word: "精美", pinyin: "jīng měi", sentence: "他的绘画作品[精]致又好看。", target: "精", targetPinyin: "jīng" },
  { unit: "2", lessonId: "7", word: "别致", pinyin: "bié zhì", sentence: "这个书包的设计非常[别致]。", target: "别致", targetPinyin: "bié zhì" },
  { unit: "2", lessonId: "7", word: "约束", pinyin: "yuē shù", sentence: "我用丝带把礼物[束]成漂亮的花结。", target: "束", targetPinyin: "shù" },
  { unit: "2", lessonId: "7", word: "搭配", pinyin: "dā pèi", sentence: "红色的裙子[配]合白色的上衣，特别好看。", target: "配", targetPinyin: "pèi" },
  { unit: "2", lessonId: "7", word: "甩开", pinyin: "shuǎi kāi", sentence: "小狗[甩]着尾巴，向我跑过来。", target: "甩", targetPinyin: "shuǎi" },
  { unit: "2", lessonId: "7", word: "丧气", pinyin: "sàng qì", sentence: "弟弟丢了玩具，一脸[丧]气的样子。", target: "丧", targetPinyin: "sàng" },
  { unit: "2", lessonId: "7", word: "追赶", pinyin: "zhuī gǎn", sentence: "小朋友们在草地上[追]着蝴蝶跑。", target: "追", targetPinyin: "zhuī" },
  { unit: "2", lessonId: "7", word: "拉扯", pinyin: "lā chě", sentence: "妹妹不小心[扯]坏了我的图画本。", target: "扯", targetPinyin: "chě" },
  { unit: "2", lessonId: "7", word: "叹气", pinyin: "tàn qì", sentence: "看到美丽的晚霞，我忍不住发出赞[叹]。", target: "叹", targetPinyin: "tàn" },
  { unit: "2", lessonId: "7", word: "逃跑", pinyin: "táo pǎo", sentence: "小老鼠看到猫，赶紧[逃]进了洞里。", target: "逃", targetPinyin: "táo" },
  { unit: "2", lessonId: "7", word: "皱纹", pinyin: "zhòu wén", sentence: "奶奶的脸上爬满了[皱]纹。", target: "皱", targetPinyin: "zhòu" },
  { unit: "2", lessonId: "7", word: "撒谎", pinyin: "sā huǎng", sentence: "小狗在家里[撒]欢地跑来跑去，瓜子撒落一地。", target: "撒", targetPinyin: "sā" },

  // 第8课《池子与河流》
  { unit: "2", lessonId: "8", word: "滔滔", pinyin: "tāo tāo", sentence: "江水[滔]滔不绝地向东流去。", target: "滔", targetPinyin: "tāo" },
  { unit: "2", lessonId: "8", word: "贯穿", pinyin: "guàn chuān", sentence: "这条铁路[贯]穿了整个城市。", target: "贯", targetPinyin: "guàn" },
  { unit: "2", lessonId: "8", word: "妇女", pinyin: "fù nǚ", sentence: "这位[妇]人为孩子撑起了雨伞。", target: "妇", targetPinyin: "fù" },
  { unit: "2", lessonId: "8", word: "垫子", pinyin: "diàn zi", sentence: "我把书[垫]在桌子脚下，让桌子平稳些。", target: "垫", targetPinyin: "diàn" },
  { unit: "2", lessonId: "8", word: "担忧", pinyin: "dān yōu", sentence: "妈妈为我的学习情况感到[忧]虑。", target: "忧", targetPinyin: "yōu" },
  { unit: "2", lessonId: "8", word: "考虑", pinyin: "kǎo lù", sentence: "做决定前，我们要仔细考[虑]后果。", target: "虑", targetPinyin: "lù" },
  { unit: "2", lessonId: "8", word: "凭借", pinyin: "píng jiè", sentence: "[凭]借努力，他终于考上了理想的学校。", target: "凭", targetPinyin: "píng" },
  { unit: "2", lessonId: "8", word: "哲理", pinyin: "zhé lǐ", sentence: "这个小故事藏着耐人寻味的[哲]理。", target: "哲", targetPinyin: "zhé" },
  { unit: "2", lessonId: "8", word: "遵循", pinyin: "zūn xún", sentence: "每个人都要[遵]守交通规则。", target: "遵", targetPinyin: "zūn" },
  { unit: "2", lessonId: "8", word: "循环", pinyin: "xún huán", sentence: "我们做事要[遵循]客观规律。", target: "遵循", targetPinyin: "zūn xún" },
  { unit: "2", lessonId: "8", word: "安逸", pinyin: "ān yì", sentence: "假期里，他过得[安逸]又快乐。", target: "安逸", targetPinyin: "ān yì" },
  { unit: "2", lessonId: "8", word: "尊重", pinyin: "zūn zhòng", sentence: "我们要[尊]敬长辈，礼貌待人。", target: "尊", targetPinyin: "zūn" },
  { unit: "2", lessonId: "8", word: "衰败", pinyin: "shuāi bài", sentence: "秋天到了，花草开始渐渐[衰]败。", target: "衰", targetPinyin: "shuāi" },

  // ================= 第三单元 =================
  // 第9课《海底世界》
  { unit: "3", lessonId: "9", word: "官员", pinyin: "guān yuán", sentence: "这位[官]员认真地为百姓解决问题。", target: "官", targetPinyin: "guān" },
  { unit: "3", lessonId: "9", word: "是否", pinyin: "shì fǒu", sentence: "你[否]定愿意和我一起去图书馆？", target: "否", targetPinyin: "fǒu" },
  { unit: "3", lessonId: "9", word: "窃听", pinyin: "qiè tīng", sentence: "他偷偷[窃]听了别人的谈话，这是不对的。", target: "窃", targetPinyin: "qiè" },
  { unit: "3", lessonId: "9", word: "私有", pinyin: "sī yǒu", sentence: "我们不能把公家的东西占为[私]有。", target: "私", targetPinyin: "sī" },
  { unit: "3", lessonId: "9", word: "汪汪", pinyin: "wāng wāng", sentence: "小狗对着陌生人[汪汪]叫个不停。", target: "汪汪", targetPinyin: "wāng wāng" },
  { unit: "3", lessonId: "9", word: "危险", pinyin: "wēi xiǎn", sentence: "独自在河边玩耍很[危]险，一定要小心。", target: "危", targetPinyin: "wēi" },
  { unit: "3", lessonId: "9", word: "险峻", pinyin: "xiǎn jùn", sentence: "登山的时候，要注意避开[险]要的山路。", target: "险", targetPinyin: "xiǎn" },
  { unit: "3", lessonId: "9", word: "肌肉", pinyin: "jī ròu", sentence: "经常锻炼能让我们的[肌]肉更结实。", target: "肌", targetPinyin: "jī" },
  { unit: "3", lessonId: "9", word: "进攻", pinyin: "jìn gōng", sentence: "战士们向敌人发起了猛烈的进[攻]。", target: "攻", targetPinyin: "gōng" },
  { unit: "3", lessonId: "9", word: "避免", pinyin: "bì miǎn", sentence: "做完作业，我就可以避[免]被妈妈批评了。", target: "免", targetPinyin: "miǎn" },
  { unit: "3", lessonId: "9", word: "浪费", pinyin: "làng fèi", sentence: "我们要节约用水，不能浪[费]资源。", target: "费", targetPinyin: "fèi" },
  { unit: "3", lessonId: "9", word: "奇异", pinyin: "qí yì", sentence: "这块石头的形状十分奇[异]，像一只小兔子。", target: "异", targetPinyin: "yì" },
  { unit: "3", lessonId: "9", word: "达到", pinyin: "dá dào", sentence: "只要坚持努力，就能[达]到自己的目标。", target: "达", targetPinyin: "dá" },
  { unit: "3", lessonId: "9", word: "收缩", pinyin: "shōu suō", sentence: "天冷了，小乌龟就会[缩]进壳里保暖。", target: "缩", targetPinyin: "suō" },
  { unit: "3", lessonId: "9", word: "差别", pinyin: "chā bié", sentence: "公司派去出差的人能力参差不齐，[差]别很大。", target: "差", targetPinyin: "chā" },
  { unit: "3", lessonId: "9", word: "海藻", pinyin: "hǎi zǎo", sentence: "池塘里的绿[藻]在阳光下显得格外绿。", target: "藻", targetPinyin: "zǎo" },
  { unit: "3", lessonId: "9", word: "细胞", pinyin: "xì bāo", sentence: "我们都是中华民族的同[胞]，要互相帮助。", target: "胞", targetPinyin: "bāo" },
  { unit: "3", lessonId: "9", word: "煤炭", pinyin: "méi tàn", sentence: "冬天里，烧[煤]可以让房间变得暖和。", target: "煤", targetPinyin: "méi" },
  { unit: "3", lessonId: "9", word: "储存", pinyin: "chǔ cún", sentence: "松鼠会在秋天[储]存松果，以备过冬。", target: "储", targetPinyin: "chǔ" },
  { unit: "3", lessonId: "9", word: "属于", pinyin: "shǔ yú", sentence: "熊猫[属]于国家一级保护动物。", target: "属", targetPinyin: "shǔ" },

  // 第10课《纸的发明》(原PDF中提取的对应课程)
  { unit: "3", lessonId: "10", word: "实验", pinyin: "shí yàn", sentence: "科学家通过实[验]来验证自己的猜想。", target: "验", targetPinyin: "yàn" },
  { unit: "3", lessonId: "10", word: "证明", pinyin: "zhèng míng", sentence: "他拿出证据，[证]明自己没有说谎。", target: "证", targetPinyin: "zhèng" },
  { unit: "3", lessonId: "10", word: "阻力", pinyin: "zǔ lì", sentence: "大树[阻]挡了狂风，保护了小树苗。", target: "阻", targetPinyin: "zǔ" },
  { unit: "3", lessonId: "10", word: "大约", pinyin: "dà yuē", sentence: "我和同学[约]定周末一起去公园玩。", target: "约", targetPinyin: "yuē" },
  { unit: "3", lessonId: "10", word: "包括", pinyin: "bāo kuò", sentence: "老师让我们把重点内容用[括]号括起来。", target: "括", targetPinyin: "kuò" },
  { unit: "3", lessonId: "10", word: "检查", pinyin: "jiǎn chá", sentence: "妈妈每天都会[检]查我的作业完成情况。", target: "检", targetPinyin: "jiǎn" },
  { unit: "3", lessonId: "10", word: "查看", pinyin: "chá kàn", sentence: "警察仔细[查]找线索，想要破案。", target: "查", targetPinyin: "chá" },
  { unit: "3", lessonId: "10", word: "错误", pinyin: "cuò wù", sentence: "他因为粗心，犯了一个严重的错[误]。", target: "误", targetPinyin: "wù" },
  { unit: "3", lessonId: "10", word: "迷路", pinyin: "mí lù", sentence: "我在森林里[迷]路了，幸好遇到了护林员。", target: "迷", targetPinyin: "mí" },
  { unit: "3", lessonId: "10", word: "逆风", pinyin: "nì fēng", sentence: "小船[逆]着水流慢慢向前行驶。", target: "逆", targetPinyin: "nì" },
  { unit: "3", lessonId: "10", word: "陌生", pinyin: "mò shēng", sentence: "来到[陌]生的城市，我感到有些紧张。", target: "陌", targetPinyin: "mò" },
  { unit: "3", lessonId: "10", word: "大概", pinyin: "dà gài", sentence: "这件事的大[概]情况，老师已经告诉我们了。", target: "概", targetPinyin: "gài" },
  { unit: "3", lessonId: "10", word: "特殊", pinyin: "tè shū", sentence: "熊猫是一种特[shū]的动物，深受大家喜爱。", target: "殊", targetPinyin: "shū" },

  // 第11课《小虾》
  { unit: "3", lessonId: "11", word: "空隙", pinyin: "kòng xì", sentence: "我的铅笔掉进了缝[隙]里，够不着了。", target: "隙", targetPinyin: "xì" },
  { unit: "3", lessonId: "11", word: "稍微", pinyin: "shāo wēi", sentence: "请[稍]等一下，我马上就来。", target: "稍", targetPinyin: "shāo" },
  { unit: "3", lessonId: "11", word: "逐渐", pinyin: "zhú jiàn", sentence: "我们要[逐]步克服学习中的困难。", target: "逐", targetPinyin: "zhú" },
  { unit: "3", lessonId: "11", word: "一副", pinyin: "yī fù", sentence: "他戴着一[副]眼镜，看起来很斯文。", target: "副", targetPinyin: "fù" },
  { unit: "3", lessonId: "11", word: "钳子", pinyin: "qián zi", sentence: "爸爸用[钳]子修理坏掉的自行车。", target: "钳", targetPinyin: "qián" },
  { unit: "3", lessonId: "11", word: "翘起", pinyin: "qiào qǐ", sentence: "小燕子[翘]着尾巴，站在电线上唱歌。", target: "翘", targetPinyin: "qiào" },
  { unit: "3", lessonId: "11", word: "拼搏", pinyin: "pīn bó", sentence: "运动员们在赛场上奋力拼[搏]。", target: "搏", targetPinyin: "bó" },
  { unit: "3", lessonId: "11", word: "捡起", pinyin: "jiǎn qǐ", sentence: "我在路边[捡]到了一个钱包，交给了警察。", target: "捡", targetPinyin: "jiǎn" },
  { unit: "3", lessonId: "11", word: "比较", pinyin: "bǐ jiào", sentence: "这个苹果比那个苹果[较]大一些。", target: "较", targetPinyin: "jiào" },
  { unit: "3", lessonId: "11", word: "腹部", pinyin: "fù bù", sentence: "青蛙的[腹]部圆鼓鼓的，看起来很可爱。", target: "腹", targetPinyin: "fù" },
  { unit: "3", lessonId: "11", word: "破卵", pinyin: "pò luǎn", sentence: "母鸡趴在鸡蛋上，等待小鸡破[卵]而出。", target: "卵", targetPinyin: "luǎn" },

  // ================= 第四单元 =================
  // 第12课《古诗三首》(原PDF第四单元映射)
  { unit: "4", lessonId: "12", word: "旧物", pinyin: "jiù wù", sentence: "我把[旧]衣服捐给了山区的小朋友。", target: "旧", targetPinyin: "jiù" },
  { unit: "4", lessonId: "12", word: "符号", pinyin: "fú hào", sentence: "这个[符]号代表着平安和吉祥。", target: "符", targetPinyin: "fú" },
  { unit: "4", lessonId: "12", word: "牧童", pinyin: "mù tóng", sentence: "[牧]童骑着黄牛，在草地上吹着笛子。", target: "牧", targetPinyin: "mù" },
  { unit: "4", lessonId: "12", word: "纷纷", pinyin: "fēn fēn", sentence: "秋天到了，落叶[纷纷]扬扬地飘下来。", target: "纷", targetPinyin: "fēn" },
  { unit: "4", lessonId: "12", word: "灵魂", pinyin: "lín hún", sentence: "英雄的[魂]灵永远活在我们心中。", target: "魂", targetPinyin: "hún" },
  { unit: "4", lessonId: "12", word: "借书", pinyin: "jiè shū", sentence: "我向同桌[借]了一块橡皮，用完就还了。", target: "借", targetPinyin: "jiè" },
  { unit: "4", lessonId: "12", word: "喝酒", pinyin: "hē jiǔ", sentence: "爷爷喜欢在饭后喝一袋[酒]。", target: "酒", targetPinyin: "jiǔ" },
  { unit: "4", lessonId: "12", word: "遥远", pinyin: "yáo yuàn", sentence: "我[遥]望着远方的群山，心里充满向往。", target: "遥", targetPinyin: "yáo" },
  { unit: "4", lessonId: "12", word: "兄弟", pinyin: "xiōng dì", sentence: "我的[兄]长总是照顾我，保护我。", target: "兄", targetPinyin: "xiōng" },
  { unit: "4", lessonId: "12", word: "相逢", pinyin: "xiāng féng", sentence: "我们在公园偶然相[逢]，聊了很久。", target: "逢", targetPinyin: "féng" },
  { unit: "4", lessonId: "12", word: "佳节", pinyin: "jiā jié", sentence: "中秋[佳]节，全家人团聚在一起吃月饼。", target: "佳", targetPinyin: "jiā" },
  { unit: "4", lessonId: "12", word: "加倍", pinyin: "jiā bèi", sentence: "过节时，我加[倍]思念家乡。", target: "倍", targetPinyin: "bèi" },

  // 第13课《纸的发明》
  { unit: "4", lessonId: "13", word: "伟大", pinyin: "wěi dà", sentence: "雷锋是一位[伟]大的共产主义战士。", target: "伟", targetPinyin: "wěi" },
  { unit: "4", lessonId: "13", word: "贡献", pinyin: "gòng xiàn", sentence: "蜜蜂为花儿传粉，做出了很大的[贡献]。", target: "贡献", targetPinyin: "gòng xiàn" },
  { unit: "4", lessonId: "13", word: "创造", pinyin: "chuàng zào", sentence: "科学家们[创]造了许多新的发明。", target: "创", targetPinyin: "chuàng" },
  { unit: "4", lessonId: "13", word: "尤其", pinyin: "yóu qí", sentence: "我爱吃草莓，[尤其]是蘸酸奶吃。", target: "尤", targetPinyin: "yóu" },
  { unit: "4", lessonId: "13", word: "保存", pinyin: "bǎo cún", sentence: "松鼠会把松果保[存]起来，留到冬天吃。", target: "存", targetPinyin: "cún" },
  { unit: "4", lessonId: "13", word: "积累", pinyin: "jī lěi", sentence: "今年他[累]计增收了三万多元。", target: "累", targetPinyin: "lěi" },
  { unit: "4", lessonId: "13", word: "改正", pinyin: "gǎi zhèng", sentence: "我[改]正了自己的错误，变得更优秀了。", target: "改", targetPinyin: "gǎi" },
  { unit: "4", lessonId: "13", word: "价格", pinyin: "jià gé", sentence: "这个玩具的[价]格很便宜，我买了一个。", target: "价", targetPinyin: "jià" },
  { unit: "4", lessonId: "13", word: "催促", pinyin: "cuī cù", sentence: "老师[cù]促学生们赶快完成作业。", target: "促", targetPinyin: "cù" },
  { unit: "4", lessonId: "13", word: "社会", pinyin: "shè huì", sentence: "我们生活在一个和谐的[社]会里。", target: "社", targetPinyin: "shè" },
  { unit: "4", lessonId: "13", word: "笨拙", pinyin: "bèn zhuō", sentence: "不怕动作[笨]拙，只怕心灵麻木。", target: "笨", targetPinyin: "bèn" },
  { unit: "4", lessonId: "13", word: "阅读", pinyin: "yuè dú", sentence: "我每天都会[阅]读课外书，增长知识。", target: "阅", targetPinyin: "yuè" },
  { unit: "4", lessonId: "13", word: "蔡伦", pinyin: "cài lún", sentence: "[蔡]伦改进了造纸术，造福了后人。", target: "蔡", targetPinyin: "cài" },
  { unit: "4", lessonId: "13", word: "切菜", pinyin: "qiē cài", sentence: "妈妈在厨房[切]菜，我饿了急切地想吃饭。", target: "切", targetPinyin: "qiē" },
  { unit: "4", lessonId: "13", word: "便宜", pinyin: "pián yi", sentence: "新开的便利店的商品很[便]宜。", target: "便", targetPinyin: "pián" },
  { unit: "4", lessonId: "13", word: "新鲜", "pinyin": "xīn xiān", sentence: "清晨的空气格外新[鲜]！", target: "鲜", targetPinyin: "xiān" },

  // 第14课《赵州桥》
  { unit: "4", lessonId: "14", word: "姓赵", pinyin: "xìng zhào", sentence: "他姓[赵]，是我们班的班长。", target: "赵", targetPinyin: "zhào" },
  { unit: "4", lessonId: "14", word: "桥梁", pinyin: "qiáo liáng", sentence: "家乡的石拱[桥]横跨在小河上，很美丽。", target: "桥", targetPinyin: "qiáo" },
  { unit: "4", lessonId: "14", word: "经济", pinyin: "jīng jì", sentence: "他经常救[济]贫困的人，很有爱心。", target: "济", targetPinyin: "jì" },
  { unit: "4", lessonId: "14", word: "设计", pinyin: "shè jì", sentence: "建筑师[设]置了一座漂亮的教学楼。", target: "设", targetPinyin: "shè" },
  { unit: "4", lessonId: "14", word: "计算", pinyin: "jì suàn", sentence: "我[计]划周末去外婆家看望她。", target: "计", targetPinyin: "jì" },
  { unit: "4", lessonId: "14", word: "历史", pinyin: "lì shǐ", sentence: "我们要学习[史]记，铭记过去的事情。", target: "史", targetPinyin: "shǐ" },
  { unit: "4", lessonId: "14", word: "坚固", pinyin: "jiān gù", sentence: "这座桥建造得很[坚]固，不怕风吹雨打。", target: "坚", targetPinyin: "jiān" },
  { unit: "4", lessonId: "14", word: "牢固", pinyin: "láo gù", sentence: "固定好桌子后，结构就更[固]了。", target: "固", targetPinyin: "gù" },
  { unit: "4", lessonId: "14", word: "而且", pinyin: "ér qiě", sentence: "这本书很有趣，[且]并且读起来也很轻松。", target: "且", targetPinyin: "qiě" },
  { unit: "4", lessonId: "14", word: "栏杆", pinyin: "lán gān", sentence: "操场边的[栏]杆刷上了新漆，很醒目。", target: "栏", targetPinyin: "lán" },
  { unit: "4", lessonId: "14", word: "宝贵", pinyin: "bǎo guì", sentence: "时间是[贵]重的，我们不能浪费。", target: "贵", targetPinyin: "guì" },
  { unit: "4", lessonId: "14", word: "历史书", pinyin: "lì shǐ shū", sentence: "这本[历]史书讲述了很多古代的故事。", target: "历", targetPinyin: "lì" },
  { unit: "4", lessonId: "14", word: "县城", pinyin: "xiàn chéng", sentence: "我的老家在一个风景优美的小[县]。", target: "县", targetPinyin: "xiàn" },
  { unit: "4", lessonId: "14", word: "工匠", pinyin: "gōng jiàng", sentence: "木[匠]师傅的手艺很高超，做的家具很漂亮。", target: "匠", targetPinyin: "jiàng" },
  { unit: "4", lessonId: "14", word: "砌墙", pinyin: "qì qiáng", sentence: "建筑工人用大理[砌]墙体结构。", target: "砌", targetPinyin: "qì" },
  { unit: "4", lessonId: "14", word: "爪子", pinyin: "zhuǎ zi", sentence: "小猫的[爪]子很小，但非常灵活。", target: "爪", targetPinyin: "zhuǎ" },
  { unit: "4", lessonId: "14", word: "抵抗", pinyin: "dǐ kàng", sentence: "战士们奋力[抵]抗敌人的进攻。", target: "抵", targetPinyin: "dǐ" },
  { unit: "4", lessonId: "14", word: "智慧", pinyin: "zhì huì", sentence: "他用[智]慧解决了学习中的难题。", target: "智", targetPinyin: "zhì" },
  { unit: "4", lessonId: "14", word: "聪慧", pinyin: "cōng huì", sentence: "奶奶虽然年纪大了，但很有[慧]心。", target: "慧", targetPinyin: "huì" },
  { unit: "4", lessonId: "14", word: "遗失", pinyin: "yí shī", sentence: "他在车站[遗]失了一个背包，很着急。", target: "遗", targetPinyin: "yí" },

  // ================= 第五单元 =================
  // 第15课《一幅名扬中外的画》(原PDF第五单元映射)
  { unit: "5", lessonId: "15", word: "选择", pinyin: "xuǎn zé", sentence: "我们要学会[择]取正确的人生道路。", target: "择", targetPinyin: "zé" },
  { unit: "5", lessonId: "15", word: "商贩", pinyin: "shāng fàn", sentence: "小[摊]贩在街边的摊位上卖着新鲜的水果。", target: "摊", targetPinyin: "tān" },
  { unit: "5", lessonId: "15", word: "贩卖", pinyin: "fàn mài", sentence: "那个人[贩]卖稀有邮票，吸引了很多人。", target: "贩", targetPinyin: "fàn" },
  { unit: "5", lessonId: "15", word: "官吏", pinyin: "guān lì", sentence: "古代的官[吏]要为百姓办实事。", target: "吏", targetPinyin: "lì" },
  { unit: "5", lessonId: "15", word: "毛驴", pinyin: "máo lú", sentence: "小毛[驴]拉着磨盘，一圈圈地转着。", target: "驴", targetPinyin: "lú" },
  { unit: "5", lessonId: "15", word: "乘车", pinyin: "chéng chē", sentence: "他每天都要[乘]车去学校。", target: "乘", targetPinyin: "chéng" },
  { unit: "5", lessonId: "15", word: "鸟笼", pinyin: "niǎo lóng", sentence: "爷爷提着鸟[笼]在院中散步。", target: "笼", targetPinyin: "lóng" },
  { unit: "5", lessonId: "15", word: "拽住", pinyin: "zhuài zhù", sentence: "弟弟用力[拽]住我的衣角，不让我走。", target: "拽", targetPinyin: "zhuài" },
  { unit: "5", lessonId: "15", word: "打扰", pinyin: "dǎ rǎo", sentence: "外面的噪音打[扰]了我的学习。", target: "扰", targetPinyin: "rǎo" },
  { unit: "5", lessonId: "15", word: "外貌", pinyin: "wài mào", sentence: "姐姐的容[貌]很清秀，性格也很温柔。", target: "貌", targetPinyin: "mào" },

  // 语文园地四(对应第五单元后半段)
  { unit: "5", lessonId: "30", word: "援助", pinyin: "yuán zhù", sentence: "大家一起[援]助灾区的小朋友。", target: "援", targetPinyin: "yuán" },
  { unit: "5", lessonId: "30", word: "投掷", pinyin: "tóu zhì", sentence: "体育课上我们练习投[掷]沙包。", target: "掷", targetPinyin: "zhì" },
  { unit: "5", lessonId: "30", word: "投入", pinyin: "tóu rù", sentence: "他认真[投]入到学习中。", target: "投", targetPinyin: "tóu" },
  { unit: "5", lessonId: "30", word: "打捞", pinyin: "dǎ lāo", sentence: "我帮弟弟[捞]起掉在水里的玩具。", target: "捞", targetPinyin: "lāo" },
  { unit: "5", lessonId: "30", word: "拆开", pinyin: "chāi kāi", sentence: "我小心[拆]开礼物盒。", target: "拆", targetPinyin: "chāi" },
  { unit: "5", lessonId: "30", word: "搅拌", pinyin: "jiǎo bàn", sentence: "妈妈用勺子[搅]伴鸡蛋。", target: "搅", targetPinyin: "jiǎo" },
  { unit: "5", lessonId: "30", word: "拓展", pinyin: "tuò zhǎn", sentence: "我们要努力开[拓]眼界。", target: "拓", targetPinyin: "tuò" },

  // ================= 第六单元 =================
  // 第16课《胡萝卜先生的长胡子》
  { unit: "6", lessonId: "16", word: "萝卜", pinyin: "luó bo", sentence: "小白兔最爱吃脆生生的胡[萝]卜。", target: "萝", targetPinyin: "luó" },
  { unit: "6", lessonId: "16", word: "占卜", pinyin: "zhān bǔ", sentence: "奶奶说用萝[卜]做菜前，要先把皮削干净。", target: "卜", targetPinyin: "bo" },
  { unit: "6", lessonId: "16", word: "发愁", pinyin: "fā chóu", sentence: "他为明天的考试感到发[愁]。", target: "愁", targetPinyin: "chóu" },
  { unit: "6", lessonId: "16", word: "浓密", pinyin: "nóng mì", sentence: "她有一头[浓]密的头发。", target: "浓", targetPinyin: "nóng" },
  { unit: "6", lessonId: "16", word: "足够", pinyin: "zú gòu", sentence: "这些零食[够]我们吃一整个下午了。", target: "够", targetPinyin: "gòu" },
  { unit: "6", lessonId: "16", word: "确实", pinyin: "què shí", sentence: "经过验证，这个消息[确]实是真的。", target: "确", targetPinyin: "què" },
  { unit: "6", lessonId: "16", word: "段落", pinyin: "duàn luò", sentence: "这篇文章可以分成三个[段]落来理解。", target: "段", targetPinyin: "duàn" },
  { unit: "6", lessonId: "16", word: "关系", pinyin: "guān xì", sentence: "她和妈妈的[系]常好。", target: "系", targetPinyin: "xì" },
  { unit: "6", lessonId: "16", word: "系鞋带", pinyin: "jì xié dài", sentence: "我终于学会了[系]紧鞋带。", target: "系", targetPinyin: "jì" },
  { unit: "6", lessonId: "16", word: "姐姐", pinyin: "jiě jie", sentence: "我的[姐]姐是一名小学老师。", target: "姐", targetPinyin: "jiě" },
  { unit: "6", lessonId: "16", word: "晾晒", pinyin: "liàng shài", sentence: "妈妈把洗好的衣服[晾]晒在阳台上。", target: "晾", targetPinyin: "liàng" },
  { unit: "6", lessonId: "16", word: "肩膀", pinyin: "jiān bǎng", sentence: "他拍了拍我的[肩]头，鼓励我继续加油。", target: "肩", targetPinyin: "jiān" },
  { unit: "6", lessonId: "16", word: "掏出", pinyin: "tāo chū", sentence: "我从书包里[掏]出了作业本。", target: "掏", targetPinyin: "tāo" },

  // 第17课《我变成了一棵树》
  { unit: "6", lessonId: "17", word: "希望", pinyin: "xī wàng", sentence: "我[希]望周末能去公园放风筝。", target: "希", targetPinyin: "xī" },
  { unit: "6", lessonId: "17", word: "担心", pinyin: "dān xīn", sentence: "妈妈总是[担]心我的身体健康。", target: "担", targetPinyin: "dān" },
  { unit: "6", lessonId: "17", word: "容易", pinyin: "róng yì", sentence: "这道数学题做起来很[容]易。", target: "容", targetPinyin: "róng" },
  { unit: "6", lessonId: "17", word: "震动", pinyin: "zhèn dòng", sentence: "四川曾经发生过多次地[震]。", target: "震", targetPinyin: "zhèn" },
  { unit: "6", lessonId: "17", word: "零钱", pinyin: "líng qián", sentence: "我口袋里有一些[零]钱。", target: "零", targetPinyin: "líng" },
  { unit: "6", lessonId: "17", word: "香肠", pinyin: "xiāng cháng", sentence: "妈妈做的香[肠]味道特别香。", target: "肠", targetPinyin: "cháng" },
  { unit: "6", lessonId: "17", word: "麻烦", pinyin: "má fan", sentence: "弟弟总是吵闹，给我添了很多[麻]烦。", target: "麻", targetPinyin: "ma" },
  { unit: "6", lessonId: "17", word: "烦恼", pinyin: "fán nǎo", sentence: "弟弟总是吵闹，让我觉得很[烦]恼。", target: "烦", targetPinyin: "fán" },
  { unit: "6", lessonId: "17", word: "嗓子", pinyin: "sǎng zi", sentence: "小红的[嗓]子哑了，说不出话。", target: "嗓", targetPinyin: "sǎng" },
  { unit: "6", lessonId: "17", word: "发痒", pinyin: "fā yǎng", sentence: "蚊子咬了我一口，皮肤特别[痒]。", target: "痒", targetPinyin: "yǎng" },
  { unit: "6", lessonId: "17", word: "椭圆", pinyin: "tuǒ yuán", sentence: "这个洞口是[椭]圆形的。", target: "椭", targetPinyin: "tuǒ" },
  { unit: "6", lessonId: "17", word: "嘴馋", pinyin: "zuǐ chán", sentence: "看到好吃的蛋糕，我嘴[chán]得直流口水。", target: "馋", targetPinyin: "chán" },

  // ================= 第七单元 =================
  // 第18课《童年的水墨画》
  { unit: "7", lessonId: "18", word: "垂柳", pinyin: "chuí liǔ", sentence: "柳树的枝条[垂]下来，在风中轻轻摇摆。", target: "垂", targetPinyin: "chuí" },
  { unit: "7", lessonId: "18", word: "染色", pinyin: "rǎn sè", sentence: "他的笑容感[染]了所有人。", target: "染", targetPinyin: "rǎn" },
  { unit: "7", lessonId: "18", word: "碎片", pinyin: "suì piàn", sentence: "他把纸撕成了好多[碎]片。", target: "碎", targetPinyin: "suì" },
  { unit: "7", lessonId: "18", word: "翅膀", pinyin: "chì bǎng", sentence: "小鸟展开[翅]膀飞走了。", target: "翅", targetPinyin: "chì" },
  { unit: "7", lessonId: "18", word: "肩膀", pinyin: "jiān bǎng", sentence: "我趴在爸爸的肩[膀]上。", target: "膀", targetPinyin: "bǎng" },
  { unit: "7", lessonId: "18", word: "拨动", pinyin: "bō dòng", sentence: "我给妈妈[拨]号打电话。", target: "拨", targetPinyin: "bō" },
  { unit: "7", lessonId: "18", word: "浪花", pinyin: "làng huā", sentence: "海浪拍打着沙滩，发出哗哗的[浪]涛声。", target: "浪", targetPinyin: "làng" },
  { unit: "7", lessonId: "18", word: "抖动", pinyin: "dǒu dòng", sentence: "我[抖]动绳子，摇下树上的果子。", target: "抖", targetPinyin: "dǒu" },
  { unit: "7", lessonId: "18", word: "墨水", pinyin: "mò shuǐ", sentence: "[墨]汁不小心洒在白纸上，染出了大墨点。", target: "墨", targetPinyin: "mò" },
  { unit: "7", lessonId: "18", word: "飞溅", pinyin: "fēi jiàn", sentence: "小石子扔进水里，水珠向四周飞[溅]开来。", target: "溅", targetPinyin: "jiàn" },

  // 第19课《肥皂泡》
  { unit: "7", lessonId: "19", word: "肥皂", pinyin: "féi zào", sentence: "我用肥[皂]把小手洗得干干净净。", target: "皂", targetPinyin: "zào" },
  { unit: "7", lessonId: "19", word: "水泡", pinyin: "shuǐ pào", sentence: "我用肥皂搅和出许多[泡]沫。", target: "泡", targetPinyin: "pào" },
  { unit: "7", lessonId: "19", word: "种类", pinyin: "zhǒng lèi", sentence: "小猫和小狗都属于动物这一[类]。", target: "类", targetPinyin: "lèi" },
  { unit: "7", lessonId: "19", word: "摆弄", pinyin: "bǎi nòng", sentence: "弟弟最喜欢[弄]乱我的积木城堡。", target: "弄", targetPinyin: "nòng" },
  { unit: "7", lessonId: "19", word: "溶解", pinyin: "róng jiě", sentence: "糖块放进热水里很快就[溶]解了。", target: "溶", targetPinyin: "róng" },
  { unit: "7", lessonId: "19", word: "外套", "pinyin": "wài tào", sentence: "冬天出门时，我会带上[套]袖。", target: "套", targetPinyin: "tào" },
  { unit: "7", lessonId: "19", word: "悠闲", pinyin: "yōu xián", sentence: "爷爷在院子里慢[悠]悠地散步。", target: "悠", targetPinyin: "yōu" },
  { unit: "7", lessonId: "19", word: "倘若", pinyin: "tǎng ruò", sentence: "你[若]是认真听讲，就能学会这道题。", target: "若", targetPinyin: "ruò" },
  { unit: "7", lessonId: "19", word: "骄傲", pinyin: "jiāo ào", sentence: "我们不能因为考了高分就[骄]傲自满。", target: "骄", targetPinyin: "jiāo" },
  { unit: "7", lessonId: "19", word: "剩下", "pinyin": "shèng xià", sentence: "蛋糕只[剩]下最后一块了，留给奶奶吧。", target: "剩", targetPinyin: "shèng" },
  { unit: "7", lessonId: "19", word: "和面", pinyin: "huó miàn", sentence: "妈妈正在厨房[和]面，准备中午包饺子。", target: "和", targetPinyin: "huó" },
  { unit: "7", lessonId: "19", word: "悬挂", pinyin: "xuán guà", sentence: "一轮明月[悬]挂在深蓝色的夜空中。", target: "悬", targetPinyin: "xuán" },
  { unit: "7", lessonId: "19", word: "婴儿", pinyin: "yīng ér", sentence: "邻居家的小[婴]儿总是咯咯地笑。", target: "婴", targetPinyin: "yīng" },

  // ================= 第八单元 =================
  // 第22课《火烧云》(对应原PDF第八单元第一课)
  { unit: "8", lessonId: "22", word: "烧火", pinyin: "shāo huǒ", sentence: "天上的晚霞通红，像是在空中燃[烧]起来了一样。", target: "烧", targetPinyin: "shāo" },
  { unit: "8", lessonId: "22", word: "充盈", pinyin: "chōng yíng", sentence: "这个月全家精打细算，月底还有不少[盈]余呢。", target: "盈", targetPinyin: "yíng" },
  { unit: "8", lessonId: "22", word: "乘车", pinyin: "chéng chē", sentence: "我们可以[乘]车去区图书馆，既省钱又低碳。", target: "乘", targetPinyin: "chéng" },
  { unit: "8", lessonId: "22", word: "长寿", pinyin: "cháng shòu", sentence: "全家人都聚在老家，一起为爷爷庆祝九十高[寿]。", target: "寿", targetPinyin: "shòu" },
  { unit: "8", lessonId: "22", word: "红彤彤", pinyin: "hóng tōng tōng", sentence: "红[彤]彤的晚霞铺满了整片天空，好看极了。", target: "彤", targetPinyin: "tóng" },
  { unit: "8", lessonId: "22", word: "颜色", pinyin: "yán sè", sentence: "雨后的天边挂着一抹[颜]色斑斓的彩虹。", target: "颜", targetPinyin: "yán" },
  { unit: "8", lessonId: "22", word: "时钟", pinyin: "shí zhōng", sentence: "这座铺天盖地的[钟]楼矗立在小镇的中心。", target: "钟", targetPinyin: "zhōng" },
  { unit: "8", lessonId: "22", word: "武术", pinyin: "wǔ shù", sentence: "操场上有不少英俊的男孩子在刻苦练习[武]术。", target: "武", targetPinyin: "wǔ" },
  { unit: "8", lessonId: "22", word: "镇静", pinyin: "zhèn jìng", sentence: "面对突发的火灾险情，我们要保持[镇]定不要慌乱。", target: "镇", targetPinyin: "zhèn" },
  { unit: "8", lessonId: "22", word: "偏旁", pinyin: "piān páng", sentence: "字典里这个汉字的[偏]旁是宝盖头，非常好查。", target: "偏", targetPinyin: "piān" },
  { unit: "8", lessonId: "22", word: "檀香", pinyin: "tán xiāng", sentence: "爷爷的红木书桌上摆着一个精致别致的[檀]木笔筒。", target: "檀", targetPinyin: "tán" },
  { unit: "8", lessonId: "22", word: "小猪", pinyin: "xiǎo zhū", sentence: "农村的外婆家喂养了几只大耳朵的可爱花[猪]。", target: "猪", targetPinyin: "zhū" },
  { unit: "8", lessonId: "22", word: "跪下", pinyin: "guì xià", sentence: "清明时节，我们会[跪]拜祖先来寄托怀念思绪。", target: "跪", targetPinyin: "guì" },
  { unit: "8", lessonId: "22", word: "寺庙", "pinyin": "sì miào", sentence: "青山深处耸立着许多古老而静谧的[庙]宇建筑。", target: "庙", targetPinyin: "miào" },
  { unit: "8", lessonId: "22", word: "揉搓", pinyin: "róu cuō", sentence: "洗手的时候要仔细[揉]搓手掌，才能洗干净。", target: "揉", targetPinyin: "róu" },

  // 第23课《暴风雨来临之前》
  { unit: "8", lessonId: "23", word: "来临", pinyin: "lái lín", sentence: "暴风雨即将[临]近前，天空变得特别沉闷窒息。", target: "临", targetPinyin: "lín" },
  { unit: "8", lessonId: "23", word: "越过", pinyin: "yuè guò", sentence: "我们要齐心协力[越]过前面那座崇高陡峭的山峰。", target: "越", targetPinyin: "yuè" },
  { unit: "8", lessonId: "23", word: "闷雷", pinyin: "mēn léi", sentence: "屋子里一点微风都没有，简直太沉[闷]闷热了。", target: "闷", targetPinyin: "mēn" },
  { unit: "8", lessonId: "23", word: "黄昏", pinyin: "huáng hūn", sentence: "天色已经[昏]暗下来，路灯陆陆续续亮了起来。", target: "昏", targetPinyin: "hūn" },
  { unit: "8", lessonId: "23", word: "黑暗", pinyin: "hēi àn", sentence: "拉上厚实的窗帘后，房间里立刻变得黑[暗]无比。", target: "暗", targetPinyin: "àn" },
  { unit: "8", lessonId: "23", word: "情况", pinyin: "qíng kuàng", sentence: "班主任老师向我询问了班里的最新学习状[况]。", target: "况", targetPinyin: "kuàng" },
  { unit: "8", lessonId: "23", word: "树梢", pinyin: "shù shāo", sentence: "一只漂亮的红雀停在微风吹拂的树[梢]上歌唱。", target: "梢", targetPinyin: "shāo" },
  { unit: "8", lessonId: "23", word: "轰隆隆", pinyin: "hōng lóng lóng", sentence: "远处的天边隐隐约约传来轰[隆]隆的低沉雷声。", target: "隆", targetPinyin: "lóng" },
  { unit: "8", lessonId: "23", word: "蔓延", pinyin: "màn yán", sentence: "潮湿的假山石壁上，绿色青苔一直在[蔓]延生长。", target: "蔓", targetPinyin: "màn" },
  { unit: "8", lessonId: "23", word: "汹涌", pinyin: "xiōng yǒng", sentence: "江水奔腾[汹]涌，拍打着江两岸的坚硬怪石。", target: "汹", targetPinyin: "xiōng" },

  // 第25课《慢性子裁缝和急性子顾客》
  { unit: "8", lessonId: "25", word: "性格", pinyin: "xìng gē", sentence: "每个人的[性]格都有自己的特点。", target: "性", targetPinyin: "xìng" },
  { unit: "8", lessonId: "25", word: "顾客", pinyin: "gù kè", sentence: "妈妈细心照[顾]着生病的奶奶。", target: "顾", targetPinyin: "gù" },
  { unit: "8", lessonId: "25", word: "夸奖", pinyin: "kuā jiǎng", sentence: "老师当众[夸]奖了认真完成作业的同学。", target: "夸", targetPinyin: "kuā" },
  { unit: "8", lessonId: "25", word: "奖励", pinyin: "jiǎng lì", sentence: "弟弟因为考试进步，得到了爸爸的[奖]励。", target: "奖", targetPinyin: "jiǎng" },
  { unit: "8", lessonId: "25", word: "承担", pinyin: "chéng dān", sentence: "他勇敢地[承]担起了小组里的主要工作。", target: "承", targetPinyin: "chéng" },
  { unit: "8", lessonId: "25", word: "袖子", "pinyin": "xiù zi", sentence: "寒风一吹，我赶紧把[袖]子拉到了手腕。", target: "袖", targetPinyin: "xiù" },
  { unit: "8", lessonId: "25", word: "衬托", "pinyin": "chèn tuō", sentence: "嫩绿的小草[衬]托出花朵更加鲜艳。", target: "衬", targetPinyin: "chèn" },
  { unit: "8", lessonId: "25", word: "衬衫", "pinyin": "chèn shān", sentence: "爸爸穿上干净的[衬衫]，看起来很精神。", target: "衬衫", targetPinyin: "chèn shān" },
  { unit: "8", lessonId: "25", word: "负责", pinyin: "fù zé", sentence: "他是一个对工作认真[负]责的人。", target: "负", targetPinyin: "fù" },
  { unit: "8", lessonId: "25", word: "责任", pinyin: "zé rèn", sentence: "我们每个人都要对自己的行为负[责]。", target: "责", targetPinyin: "zé" },
  { unit: "8", lessonId: "25", word: "泄露", pinyin: "xiè lù", sentence: "他不小心[泄]露了这次比赛的小秘密。", target: "泄", targetPinyin: "xiè" },
  { unit: "8", lessonId: "25", word: "恼火", pinyin: "nǎo huǒ", sentence: "弟弟把玩具弄坏了，爸爸有些[恼]火。", target: "恼", targetPinyin: "nǎo" },
  { unit: "8", lessonId: "25", word: "缝补", pinyin: "féng bǔ", sentence: "奶奶戴着老花镜，认真地[缝]补我的袜子。", target: "缝", targetPinyin: "féng" },
  { unit: "8", lessonId: "25", word: "箱子", pinyin: "xiāng zi", sentence: "我把课外书都整理进了小[箱]子里。", target: "箱", targetPinyin: "xiāng" },
  { unit: "8", lessonId: "25", word: "夹子", pinyin: "jiā zi", sentence: "书页里[夹]着一片漂亮的枫叶书签。", target: "夹", targetPinyin: "jiá" },
  { unit: "8", lessonId: "25", word: "惊讶", pinyin: "jīng yà", sentence: "看到好久不见的朋友，我露出了惊[讶]的表情。", target: "讶", targetPinyin: "yà" },

  // 第26课《漏》
  { unit: "8", lessonId: "26", word: "漏水", pinyin: "lòu shuǐ", sentence: "水管坏了，一直往地上[漏]水。", target: "漏", targetPinyin: "lòu" },
  { unit: "8", lessonId: "26", word: "胖子", pinyin: "pàng zi", sentence: "小熊吃得圆滚滚的，是个小[胖]子。", target: "胖", targetPinyin: "pàng" },
  { unit: "8", lessonId: "26", word: "毛驴", pinyin: "máo lǘ", sentence: "爷爷牵着毛[驴]，去村口拉粮食。", target: "驴", targetPinyin: "lǘ" },
  { unit: "8", lessonId: "26", word: "莫要", pinyin: "mò yào", sentence: "你[莫]要着急，事情总会解决的。", target: "莫", targetPinyin: "mò" },
  { unit: "8", lessonId: "26", word: "严厉", pinyin: "yán lì", sentence: "老师的表情很严[厉]，同学们都坐直了。", target: "厉", targetPinyin: "lì" },
  { unit: "8", lessonId: "26", word: "伤害", pinyin: "shāng hài", sentence: "我们要爱护小动物，不要伤[害]它们。", target: "害", targetPinyin: "hài" },
  { unit: "8", lessonId: "26", word: "闯祸", pinyin: "chuǎng huò", sentence: "弟弟调皮，不小心[闯]祸了。", target: "闯", targetPinyin: "chuǎng" },
  { unit: "8", lessonId: "26", word: "抚摸", pinyin: "fǔ mō", sentence: "妈妈温柔地[抚]摸着我的头。", target: "摸", targetPinyin: "mō" },
  { unit: "8", lessonId: "26", word: "歪斜", "pinyin": "wāi xié", sentence: "桌子没放稳，有点[歪]斜。", target: "歪", targetPinyin: "wāi" },
  { unit: "8", lessonId: "26", word: "胶水", pinyin: "jiāo shuǐ", sentence: "我用[胶]水把断了的铅笔粘好了。", target: "胶", targetPinyin: "jiāo" },
  { unit: "8", lessonId: "26", word: "纵身", pinyin: "zòng shēn", sentence: "小松鼠[纵]身一跃，跳到了树枝上。", target: "纵", targetPinyin: "zòng" },
  { unit: "8", lessonId: "26", word: "脊背", pinyin: "jǐ bèi", sentence: "爸爸的[脊]背宽厚，能给我安全感。", target: "脊", targetPinyin: "jǐ" },
  { unit: "8", lessonId: "26", word: "盗贼", pinyin: "dào zéi", sentence: "警察叔叔抓住了偷东西的[贼]。", target: "贼", targetPinyin: "zei" },
  { unit: "8", lessonId: "26", word: "头晕", pinyin: "tóu yūn", sentence: "早上没吃饭，我有点头[晕]。", target: "晕", targetPinyin: "yūn" },
  { unit: "8", lessonId: "26", word: "颠簸", pinyin: "diān bǒ", sentence: "山路不平，车子开起来特别[颠]簸。", target: "颠", targetPinyin: "diān" },
  { unit: "8", lessonId: "26", word: "旋风", pinyin: "xuàn fēng", sentence: "一阵[旋]风刮过，地上的落叶都被卷了起来。", target: "旋", targetPinyin: "xuàn" },
  { unit: "8", lessonId: "26", word: "嫌弃", pinyin: "xián qì", sentence: "奶奶做的饭很香，没人会[嫌]弃。", target: "嫌", targetPinyin: "xián" },

  // 第27课《枣核》
  { unit: "8", lessonId: "27", word: "核心", pinyin: "hé xīn", sentence: "团结是一个团队的[核]心力量。", target: "核", targetPinyin: "hé" },
  { unit: "8", lessonId: "27", word: "夫妻", pinyin: "fū qī", sentence: "爸爸和妈妈是恩爱和睦的夫[妻]。", target: "妻", targetPinyin: "qī" },
  { unit: "8", lessonId: "27", word: "爹爹", pinyin: "diē die", sentence: "小时候，[爹]爹总背着我去村口玩。", target: "爹", targetPinyin: "diē" },
  { unit: "8", lessonId: "27", word: "犁地", pinyin: "lí dì", sentence: "春天到了，农民伯伯牵着牛去田里[犁]地。", target: "犁", targetPinyin: "lí" },
  { unit: "8", lessonId: "27", word: "聪明", pinyin: "cōng mǐng", sentence: "妹妹既[聪]明又懂事，大家都很喜欢她。", target: "聪", targetPinyin: "cōng" },
  { unit: "8", lessonId: "27", word: "干旱", pinyin: "gān hàn", sentence: "这片田地因为干[旱]，庄稼长得不好。", target: "旱", targetPinyin: "hàn" },
  { unit: "8", lessonId: "27", word: "收纳", pinyin: "shōu nà", sentence: "我把散落的玩具收[纳]进了整理箱。", target: "纳", targetPinyin: "nà" },
  { unit: "8", lessonId: "27", word: "搜寻", pinyin: "sōu xún", sentence: "警察叔叔在树林里[搜]寻走失的小朋友。", target: "搜", targetPinyin: "sōu" },
  { unit: "8", lessonId: "27", word: "折腾", pinyin: "zhē teng", sentence: "弟弟总爱[折]腾玩具，把房间弄得乱糟糟的。", target: "折", targetPinyin: "zhē" },
  { unit: "8", lessonId: "27", word: "困难", pinyin: "kùn nan", sentence: "遇到[困]难时，我们要想办法勇敢克服。", target: "困", targetPinyin: "kùn" },
  { unit: "8", lessonId: "27", word: "岂非", pinyin: "qǐ fēi", sentence: "你这样随意破坏公物，[岂]非岂有此理！", target: "岂", targetPinyin: "qǐ" },
  { unit: "8", lessonId: "27", word: "涨潮", pinyin: "zhǎng cháo", sentence: "海边的潮水慢慢[涨]潮，漫过了沙滩。", target: "涨", targetPinyin: "zhǎng" },

  // 语文园地八
  { unit: "8", lessonId: "28", word: "咳嗽", pinyin: "ké sou", sentence: "天冷着凉，他忍不住[咳]嗽了几声。", target: "咳", targetPinyin: "ké" },
  { unit: "8", lessonId: "28", word: "咳嗽", pinyin: "ké sou", sentence: "奶奶感冒后，一直咳[嗽]不停。", target: "嗽", targetPinyin: "sòu" },
  { unit: "8", lessonId: "28", word: "唠叨", pinyin: "láo dao", sentence: "妈妈总爱[唠]叨我，让多穿点衣服。", target: "唠", targetPinyin: "láo" },
  { unit: "8", lessonId: "28", word: "叨念", "pinyin": "dāo niàn", sentence: "爷爷年纪大了，总爱跟我[叨]念过去的事。", target: "叨", targetPinyin: "dāo" },
  { unit: "8", lessonId: "28", word: "吆喝", pinyin: "yāo he", sentence: "小贩在街边[吆]喝着，招揽顾客。", target: "吆", targetPinyin: "yāo" },
  { unit: "8", lessonId: "28", word: "讽刺", pinyin: "fěng cì", sentence: "我们不能用话语[讽]刺别人的缺点。", target: "讽", targetPinyin: "fěng" },
  { unit: "8", lessonId: "28", word: "告诫", pinyin: "gào jiè", sentence: "老师告[诫]我们，做事要认真踏实。", target: "诫", targetPinyin: "jiè" },
  { unit: "8", lessonId: "28", word: "辩论", pinyin: "biàn lùn", sentence: "课堂上，同学们围绕问题展开了激烈的[辩]论。", target: "辩", targetPinyin: "biàn" }
];
